In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pickle
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn import metrics

In [0]:
X = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Datasets/train_data.csv")
y = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Datasets/train_label.csv")
scaler = Normalizer().fit(X)
x = scaler.transform(X)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, 
                                                    random_state=0)

In [13]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [0]:
y_pred = model.predict(X_test)

In [15]:
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

Accuracy = 0.9763292207531247
Confusion Matrix =
 [[ 4721    11     7   129     0]
 [    2 17984     3     1     0]
 [    7     8   309     5     0]
 [  410     0     0  1280     0]
 [    5     0     0     1     0]]
Recall = 0.9763292207531247
Classification Report =
               precision    recall  f1-score   support

           0       0.92      0.97      0.94      4868
           1       1.00      1.00      1.00     17990
           2       0.97      0.94      0.95       329
           3       0.90      0.76      0.82      1690
           4       0.00      0.00      0.00         6

   micro avg       0.98      0.98      0.98     24883
   macro avg       0.76      0.73      0.74     24883
weighted avg       0.98      0.98      0.98     24883



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
file = "/content/drive/My Drive/Colab Notebooks/Pickle Models/knn.pkl"
with open(file, "wb") as f:
    pickle.dump(model, f)