In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import pickle as p
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [0]:
X = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/train_data.csv')
y = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/train_label.csv')
scaler = Normalizer().fit(X)
x = scaler.transform(X)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, 
                                                    random_state=0)
y_train = np.array(y_train)

In [5]:
model = RandomForestClassifier(n_estimators=20, max_depth=20, random_state=0)
model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=20, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [0]:
y_pred = model.predict(X_test)

In [7]:
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

Accuracy = 0.9802676526142347
Confusion Matrix =
 [[ 4598     1     1   268     0]
 [    2 17987     1     0     0]
 [    2     0   326     1     0]
 [  213     0     0  1477     0]
 [    2     0     0     0     4]]
Recall = 0.9802676526142347
Classification Report =
               precision    recall  f1-score   support

           0       0.95      0.94      0.95      4868
           1       1.00      1.00      1.00     17990
           2       0.99      0.99      0.99       329
           3       0.85      0.87      0.86      1690
           4       1.00      0.67      0.80         6

   micro avg       0.98      0.98      0.98     24883
   macro avg       0.96      0.90      0.92     24883
weighted avg       0.98      0.98      0.98     24883



In [0]:
file = "/content/drive/My Drive/Colab Notebooks/Pickle Models/DT.pkl"
with open(file, "wb") as f:
    p.dump(model, f)