In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import pickle as p
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [0]:
X = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/train_data.csv')
y = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/train_label.csv')

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, 
                                                    random_state=0)
y_train = np.array(y_train)

In [5]:
model = GaussianNB()
model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = model.predict(X_test)

In [7]:
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

Accuracy = 0.678776674838243
Confusion Matrix =
 [[ 1840   719   170  2130     9]
 [   82 13210  4604    89     5]
 [    0     0   328     1     0]
 [    0    50   126  1508     6]
 [    0     1     0     1     4]]
Recall = 0.678776674838243
Classification Report =
               precision    recall  f1-score   support

           0       0.96      0.38      0.54      4868
           1       0.94      0.73      0.83     17990
           2       0.06      1.00      0.12       329
           3       0.40      0.89      0.56      1690
           4       0.17      0.67      0.27         6

   micro avg       0.68      0.68      0.68     24883
   macro avg       0.51      0.73      0.46     24883
weighted avg       0.90      0.68      0.74     24883



In [0]:
file = "/content/drive/My Drive/Colab Notebooks/Pickle Models/NB.pkl"
with open(file, "wb") as f:
    p.dump(model, f)