In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import pickle as p
from sklearn.model_selection import train_test_split
from  sklearn.linear_model import SGDClassifier
from sklearn import metrics

In [0]:
x=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/train_data.csv')
y=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/train_label.csv')

In [0]:
lr = SGDClassifier(loss="log", penalty="l2", max_iter=2)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, 
                                                    random_state=0)
y_train = np.array(y_train)

In [0]:
lr.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=2,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
y_pred = lr.predict(X_test)

In [0]:
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

Accuracy = 0.8784310573483904
Confusion Matrix =
 [[ 3564   458   193   653     0]
 [    2 17702   139   139     8]
 [   34   178    45    72     0]
 [ 1102    33     8   547     0]
 [    5     0     0     1     0]]
Recall = 0.8784310573483904
Classification Report =
               precision    recall  f1-score   support

           0       0.76      0.73      0.74      4868
           1       0.96      0.98      0.97     17990
           2       0.12      0.14      0.13       329
           3       0.39      0.32      0.35      1690
           4       0.00      0.00      0.00         6

   micro avg       0.88      0.88      0.88     24883
   macro avg       0.45      0.44      0.44     24883
weighted avg       0.87      0.88      0.88     24883



In [0]:
file = "/content/drive/My Drive/Colab Notebooks/Pickle Models/SGD.pkl"
with open(file, "wb") as f:
    p.dump(lr, f)