In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import pickle as p
import h5py
from sklearn import metrics
from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Convolution1D, Dense, Dropout, MaxPooling1D, LSTM

Using TensorFlow backend.


In [0]:
X=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/test_data.csv')
y=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/test_label.csv')
scaler = Normalizer().fit(X)
x = scaler.transform(X)

# KNN

In [0]:
with open("/content/drive/My Drive/Colab Notebooks/Pickle Models/knn.pkl", "rb")as f:
    knn = p.load(f)

In [0]:
y_knn = knn.predict(x)

In [0]:
print("Accuracy =", metrics.accuracy_score(y, y_knn))
print("Confusion Matrix =\n", metrics.confusion_matrix(y, y_knn))
print("Classification Report =\n", metrics.classification_report(y, y_knn))

Accuracy = 0.9768350319904833
Confusion Matrix =
 [[11880    17    12   293     1]
 [   11 44889     6     1     0]
 [   18    27   767    12     0]
 [ 1020     5     6  3225     0]
 [   12     0     0     0     4]]
Classification Report =
               precision    recall  f1-score   support

           0       0.92      0.97      0.94     12203
           1       1.00      1.00      1.00     44907
           2       0.97      0.93      0.95       824
           3       0.91      0.76      0.83      4256
           4       0.80      0.25      0.38        16

   micro avg       0.98      0.98      0.98     62206
   macro avg       0.92      0.78      0.82     62206
weighted avg       0.98      0.98      0.98     62206



# CNN

In [0]:
#scaler = Normalizer().fit(x)
#X = scaler.transform(x)

In [0]:
y_test = np.array(y)
X = np.array(x)
X_test = np.reshape(X, (X.shape[0],X.shape[1],1))

In [0]:
lstm_output_size = 70

In [0]:
cnn = Sequential()
cnn.add(Convolution1D(64, 3, activation="relu", input_shape=(41, 1)))
cnn.add(Convolution1D(64, 3, activation="relu"))
cnn.add(MaxPooling1D(pool_size=2))
cnn.add(Convolution1D(128, 3, activation="relu"))
cnn.add(Convolution1D(128, 3, activation="relu"))
cnn.add(MaxPooling1D(pool_size=2))
cnn.add(LSTM(lstm_output_size))
cnn.add(Dropout(0.1))
cnn.add(Dense(5, activation="softmax"))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [0]:
cnn.load_weights("/content/drive/My Drive/Colab Notebooks/HDF5 Models/checkpoint-09.hdf5")
cnn.compile(loss="sparse_categorical_crossentropy", optimizer="SGD", 
            metrics=['accuracy'])
print("Created model and loaded weights from file")

Created model and loaded weights from file


In [0]:
y_cnn = cnn.predict_classes(X_test)

In [0]:
print("Accuracy =", metrics.accuracy_score(y, y_cnn))
print("Confusion matrix =\n", metrics.confusion_matrix(y, y_cnn))
print("Classification Report =\n", metrics.classification_report(y, y_cnn))

Accuracy = 0.9667877696685208
Confusion matrix =
 [[11396    46    38   723     0]
 [   31 44714    44   118     0]
 [   43    83   685    13     0]
 [  886     0    25  3345     0]
 [   14     0     0     2     0]]
Classification Report =
               precision    recall  f1-score   support

           0       0.92      0.93      0.93     12203
           1       1.00      1.00      1.00     44907
           2       0.86      0.83      0.85       824
           3       0.80      0.79      0.79      4256
           4       0.00      0.00      0.00        16

   micro avg       0.97      0.97      0.97     62206
   macro avg       0.72      0.71      0.71     62206
weighted avg       0.97      0.97      0.97     62206



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# SGD

In [0]:
with open("/content/drive/My Drive/Colab Notebooks/Pickle Models/SGD.pkl", "rb")as f:
    sgd = p.load(f)

In [0]:
y_sgd = sgd.predict(x)

In [0]:
print("Accuracy =", metrics.accuracy_score(y, y_sgd))
print("Confusion Matrix =\n", metrics.confusion_matrix(y, y_sgd))
print("Classification Report =\n", metrics.classification_report(y, y_sgd))

Accuracy = 0.8637751985339035
Confusion Matrix =
 [[ 9578   704  1027   894     0]
 [  131 43989   749    38     0]
 [  128   471   116   109     0]
 [ 2955    96  1156    49     0]
 [   14     0     1     1     0]]
Classification Report =
               precision    recall  f1-score   support

           0       0.75      0.78      0.77     12203
           1       0.97      0.98      0.98     44907
           2       0.04      0.14      0.06       824
           3       0.04      0.01      0.02      4256
           4       0.00      0.00      0.00        16

   micro avg       0.86      0.86      0.86     62206
   macro avg       0.36      0.38      0.36     62206
weighted avg       0.85      0.86      0.86     62206



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Random Forest

In [0]:
with open("/content/drive/My Drive/Colab Notebooks/Pickle Models/RF.pkl", "rb") as f:
    rf = p.load(f)

In [0]:
y_rf = rf.predict(x)

In [0]:
print("Accuracy =", metrics.accuracy_score(y, y_rf))
print("Confusion Matrix =\n", metrics.confusion_matrix(y, y_rf))
print("Classification Report =\n", metrics.classification_report(y, y_rf))

Accuracy = 0.9638137800212199
Confusion Matrix =
 [[12056    50    29    68     0]
 [   92 44809     5     1     0]
 [   82    66   643    33     0]
 [ 1785     1    23  2447     0]
 [   13     0     0     3     0]]
Classification Report =
               precision    recall  f1-score   support

           0       0.86      0.99      0.92     12203
           1       1.00      1.00      1.00     44907
           2       0.92      0.78      0.84       824
           3       0.96      0.57      0.72      4256
           4       0.00      0.00      0.00        16

   micro avg       0.96      0.96      0.96     62206
   macro avg       0.75      0.67      0.70     62206
weighted avg       0.97      0.96      0.96     62206



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
